// Copyright 2023 Biocoder.h <biocoder.h@gmail.com>

#pragma once

#define MK_COMBINED
#define MK_C_OFFSET_UNMOD 4
#define MK_C_OFFSET_0 3
#define MK_C_OFFSET_1 5
#define MK_C_OFFSET_2 8

#define TAPPING_TERM 200
#define LEADER_TIMEOUT 300

#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_NUMERIC
#define NO_AUTO_SHIFT_SPECIAL
#define RETRO_SHIFT 250

#define TAP_HOLD_LAYER_TERM 300
#define TAP_HOLD_BOOT_TERM 500
#define TAP_HOLD_REBOOT_TERM 1000
#define TAP_HOLD_CAPS_WORD_TERM 200
#define TAP_HOLD_CAPS_LOCK_TERM 400
#define TAP_HOLD_LEADER_TERM 200
#define TAP_HOLD_SLEEP_TERM 500
#define TAP_HOLD_PWR_TERM 1000

#define OS_KEYS_WIN_UNDO C(KC_Z)
#define OS_KEYS_WIN_CUT C(KC_X)
#define OS_KEYS_WIN_COPY C(KC_C)
#define OS_KEYS_WIN_PASTE C(KC_V)
#define OS_KEYS_WIN_AGIN C(KC_Y)

#define OS_KEYS_MAC_UNDO LCMD(KC_Z)
#define OS_KEYS_MAC_CUT LCMD(KC_X)
#define OS_KEYS_MAC_COPY LCMD(KC_C)
#define OS_KEYS_MAC_PASTE LCMD(KC_V)
#define OS_KEYS_MAC_AGIN SCMD(KC_Z)

#define OS_KEYS_AUTO_SHIFT
