CONSOLE_ENABLE = no
LTO_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
PROGRAMMABLE_BUTTON_ENABLE = yes
OS_DETECTION_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes

INTROSPECTION_KEYMAP_C = biocoderh.c

OS_KEYS_ENABLE = yes
TAP_HOLD_ENABLE = yes

include $(USER_PATH)/post_rules.mk
