name: Keymap lint

permissions:
  contents: read

on:
  push:
    paths:
      - 'keymap/**'
  pull_request:
    paths:
      - 'keymap/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: QMK lint
      run: ./keyboards lint scylla biocoderh
