name: Scylla lint

permissions:
  contents: read

on:
  push:
    paths:
      - 'scylla/**'
  pull_request:
    paths:
      - 'scylla/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: QMK firmware update
      run: ./keyboards update

    - name: QMK lint
      run: |
        for dir in scylla/keymaps/*/; do
          ./keyboards lint scylla "$dir"
        done
        
